In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4])

In [3]:
arr1

array([1, 2, 3, 4])

In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [21]:
arr2  = np.array([[1, 2], [3, 4]])

In [6]:
arr2

array([[1, 2],
       [3, 4]])

In [23]:
arr3 = np.array([[[1,2]]])

In [20]:
arr2

NameError: name 'arr2' is not defined

In [9]:
arr3

array([[[1, 2]]])

In [10]:
arr.shape

NameError: name 'arr' is not defined

In [26]:
arr2.size

4

In [22]:
arr2.shape

(2, 2)

In [24]:
arr3.shape

(1, 1, 2)

In [25]:
arr3.size

2

In [ ]:
arr2.size

In [28]:
arr0 = np.zeros((2,3))

In [29]:
arr0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr1 = np.ones((2,3))

In [ ]:
arr1

In [30]:
arr15 = np.arange(15)

In [31]:
arr15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
arrc = np.array([1 + 5j,2,3], dtype = complex)
arrc

array([1.+5.j, 2.+0.j, 3.+0.j])

In [36]:
ran = np.random.rand(2,3)
ran

array([[0.53023059, 0.84507687, 0.65363894],
       [0.26575339, 0.45241365, 0.37434542]])

In [37]:
c = np.linspace(2,3,num=5)
c

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [38]:
d = np.linspace(1,10,num=2)
d

array([ 1., 10.])

In [39]:
d = np.linspace(1, 10, num=10)
d

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
r = np.zeros((2,3))
r

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
s = r.reshape((3,2))
s

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [45]:
r.reshape((2,3))
r

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
r.reshape(3,2)

In [ ]:
f = np.random.rand(4)
f

In [ ]:
f.reshape(2,2)

In [ ]:
f

In [ ]:
f.reshape(4,1)

In [51]:
g = np.random.rand(5)
g


array([0.7611181 , 0.51038666, 0.05915374, 0.96929915, 0.5064139 ])

In [52]:
g.reshape(5,1)

array([[0.7611181 ],
       [0.51038666],
       [0.05915374],
       [0.96929915],
       [0.5064139 ]])

In [53]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
x+y

array([ 6,  8, 10, 12])

In [ ]:
prod = x*y
prod

In [ ]:
div = x/y
div

In [ ]:
div = x//y
div

In [ ]:
rem = x%y
rem

In [54]:
x*x

array([ 1,  4,  9, 16])

In [55]:
x**2

array([ 1,  4,  9, 16], dtype=int32)

In [56]:
sine=np.sin(x)
sine

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
cosine=np.cos(x)
cosine

In [ ]:
deg = np.sin(2*3.14*x)
deg

In [62]:
ang = np.array([30, 45, 60, 90])
ang

array([30, 45, 60, 90])

In [67]:
sine = np.sin(2*np.pi*ang)

In [68]:
sine

array([-2.15587355e-14, -3.91639383e-15, -4.31174710e-14, -7.83278767e-15])

In [ ]:
sin2 = np.sin(2*np.pi*ang)
sin2

In [ ]:
ang = ang*180//np.pi
ang

In [ ]:
sine = np.sin(ang)

In [ ]:
sine

In [ ]:
arr = np.linspace(-1,1,)
arr

In [69]:
np.sin(30)

-0.9880316240928618

In [70]:
np.sin(2*np.pi*30)

-2.1558735510086122e-14

In [71]:
np.sin(0)

0.0

In [72]:
np.sin(np.pi/6)

0.49999999999999994

In [73]:
a = np.arange(0,15,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [74]:
a = np.array([1,2,3,4,5,6]).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
a = np.array([[[1,2], [3,4]]])
a

array([[[1, 2],
        [3, 4]]])

In [83]:
a = np.array([[[1,2]],[[5,6]], [[3,4]]])
a

array([[[1, 2]],

       [[5, 6]],

       [[3, 4]]])

In [84]:
a.ndim

3

In [87]:
z = np.array([1,2], dtype=int)
z

array([1, 2])

In [89]:
o = np.array([1,2], dtype=int)
o

array([1, 2])

In [90]:
p = np.array([1,2], dtype="float64")
p

array([1., 2.])

In [91]:
p.dtype

dtype('float64')

In [ ]:
q = np.array([1,2], dtype="int64")
q

In [ ]:
q.dtype

In [92]:
h = np.array([1,2], dtype="complex64")
h

array([1.+0.j, 2.+0.j], dtype=complex64)

In [93]:
h = np.array([1,2], dtype="complex128")
h

array([1.+0.j, 2.+0.j])

In [ ]:
h.dtype

In [94]:
h.itemsize

16

In [ ]:
p.itemsize

In [95]:
h.data

In [96]:
t = np.zeros([3,2,3])
t

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
a = np.linspace(-1,1,20)
a

In [ ]:
sine = np.sin(2*np.pi*a)

In [ ]:
sine

In [ ]:
sine.max

In [ ]:
sine[0]

In [ ]:
sine[0:8]

In [ ]:
sine[0:8:2]

In [ ]:
sine[-1::-1]

In [ ]:
a = np.arange(20)
a

In [ ]:
itemindex = np.where(a==3)
itemindex

In [ ]:
sine = sine[-1::-1]
sine

In [ ]:
item = np.where(sine==1.64594590e-01)
item

In [ ]:
a=a[::-1]
itemindex = np.where(a==3)

In [ ]:
f = np.random.random((2,3))
f

In [ ]:
f = np.random.rand((5))
f

In [ ]:
f = np.random.random((3,4))
f

In [ ]:
g = np.ravel(f)

Convert to one dimension

In [ ]:
g

In [ ]:
import time

In [ ]:
size = 1000000

In [ ]:
def list_function():
    start = time.time()
    l1 = list(range(size))
    l2=list(range(size))
    for i in range(len(l1)):
        j = l1[i]+l2[i]
    print(time.time()-start)

In [ ]:
def numpy_function():
    start = time.time()
    arr1 = np.arange(size)
    arr2 = np.arange(size)
    result = arr1+arr2
    print(time.time()-start)

In [ ]:
list_function()

In [ ]:
numpy_function()

In [ ]:
a = np.arange(4).reshape(2,2)
b = np.arange(4,8).reshape(2,2)
np.hstack((a,b))


In [ ]:
np.column_stack((a,b))

In [ ]:
np.vstack((a,b))

In [ ]:
np.row_stack((a,b))

In [ ]:
a

In [ ]:
np.hsplit(a,1)

In [ ]:
np.hsplit(a,2)

In [1]:
import numpy 

In [2]:
m, n = int(input().split())
a = input().strip().split()

a = numpy.array(a,dtype=int32).reshape((m,n))


# print(numpy.transpose(b))


2 2


TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [12]:
import numpy as np

In [109]:
dim = (map(int, input().split()))
row_1 = np.array(list(map(int, input().split())))
row_2 = np.array(list(map(int, input().split())))

2 2
1 2
3 4


In [106]:
dim

In [110]:
row = row_1 + row_2

In [111]:
row

array([4, 6])

In [112]:
row = np.array(row)

In [113]:
row

array([4, 6])

In [114]:
a, b = dim

In [115]:
print(a,b )

2 2


In [119]:
row

array([4, 6])